# Configuration for Uchiwa
---

- name: Create configuration file for uchiwa
  template:
    src=uchiwa.json.j2
    dest=/etc/sensu/uchiwa.json
    owner=uchiwa
    group=uchiwa
    mode=0640
  notify:
    - restart uchiwa

- name: Start firewalld service
  service: name=firewalld enabled=yes state=started

- name: Open firewalld to allow traffic to Uchiwa dashboard
  firewalld: port={{port}}/tcp permanent=true immediate=true state=enabled
  
- name: Start the Uchiwa service
  service: name=uchiwa enabled=yes state=started
